# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: water_arm
  joint_model_group_pose: water_start
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - sensor_joint1
    - sensor_joint2
    - sensor_joint3
    - sensor_joint4
    - water_joint1
    - water_joint2
    - water_joint3
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
watering_arm_controller:
  type: position_controllers/JointPositionController
  joints:
    - water_joint1
    - water_joint2
  gains:
    water_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    water_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
sensor_arm_controller:
  type: position_controllers/JointPositionController
  joints:
    - sensor_joint1
    - sensor_joint2
    - sensor_joint3
    - sensor_joint4
  gains:
    sensor_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    sensor_joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    sensor_joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    sensor_joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1